20
1
5000
610815
Extracting tf-idf features for NMF...
done in 3047.378s.
5000
Fitting the NMF model with tf-idf features, n_samples=1000 and n_features=5000...
done in 794.970s.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 366, in _handle_workers
    pool._maintain_pool()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 240, in _maintain_pool
    self._repopulate_pool()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Traceback (most recent call last):
  File "/home/galm/projects/cc-topography/code/nmf.py", line 203, in <module>
    main()
  File "/home/galm/projects/cc-topography/code/nmf.py", line 185, in main
    docset=abstracts, docUTset=ids,topic_ids=topic_ids),docs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 599, in get
    raise self._value
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 383, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/reduction.py", line 53, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.4/pickle.py", line 412, in dump
    self.save(obj)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 744, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 729, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 729, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.4/dist-packages/dill/dill.py", line 966, in save_functor
    log.info("Fu: %s" % obj)
MemoryError
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/util.py", line 252, in _run_finalizers
    finalizer()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/util.py", line 185, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 544, in _terminate_pool
    p.terminate()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/process.py", line 113, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
20
2
5000
610815
Extracting tf-idf features for NMF...
done in 3109.735s.
5000
Fitting the NMF model with tf-idf features, n_samples=1000 and n_features=5000...
done in 357.440s.
Traceback (most recent call last):
  File "/home/galm/projects/cc-topography/code/nmf.py", line 203, in <module>
    main()
  File "/home/galm/projects/cc-topography/code/nmf.py", line 185, in main
    docset=abstracts, docUTset=ids,topic_ids=topic_ids),docs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 599, in get
    raise self._value
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 383, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/reduction.py", line 53, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.4/pickle.py", line 412, in dump
    self.save(obj)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 744, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 729, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 729, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.4/dist-packages/dill/dill.py", line 966, in save_functor
    log.info("Fu: %s" % obj)
MemoryError
20
1
10000
610815
Extracting tf-idf features for NMF...
done in 2927.487s.
10000
Fitting the NMF model with tf-idf features, n_samples=1000 and n_features=10000...
done in 792.203s.
Process ForkPoolWorker-16:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 108, in worker
    task = get()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/queues.py", line 355, in get
    res = self._reader.recv_bytes()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/connection.py", line 219, in recv_bytes
    return buf.getvalue()
MemoryError
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 366, in _handle_workers
    pool._maintain_pool()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 240, in _maintain_pool
    self._repopulate_pool()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Traceback (most recent call last):
  File "/home/galm/projects/cc-topography/code/nmf.py", line 203, in <module>
    main()
  File "/home/galm/projects/cc-topography/code/nmf.py", line 185, in main
    docset=abstracts, docUTset=ids,topic_ids=topic_ids),docs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 599, in get
    raise self._value
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 383, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/reduction.py", line 53, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/lib/python3.4/pickle.py", line 412, in dump
    self.save(obj)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 744, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 729, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.4/pickle.py", line 729, in save_tuple
    save(element)
  File "/usr/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.4/dist-packages/dill/dill.py", line 966, in save_functor
    log.info("Fu: %s" % obj)
MemoryError
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/util.py", line 252, in _run_finalizers
    finalizer()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/util.py", line 185, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/pool.py", line 544, in _terminate_pool
    p.terminate()
  File "/usr/local/lib/python3.4/dist-packages/multiprocess/process.py", line 113, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
20
2
10000
610815
Extracting tf-idf features for NMF...
done in 3126.558s.
10000
Fitting the NMF model with tf-idf features, n_samples=1000 and n_features=10000...
done in 327.902s.
